### ISSUE TITLE
下载工具又凉凉了

### ISSUE THREAD

**Issue by itq5** [shylocks/51zhy_pdf#10]
下载工具又凉凉了
2020年2月7日14:44:27

**Comment by shylocks** [comment]
![image](https://user-images.githubusercontent.com/5812638/74007180-a89ea200-49b8-11ea-84ac-338f31b9a9ee.png)
测试正常，接口返回速度可能比较慢，需要多试一下

**Comment by shylocks** [comment]
如果仍有问题，请附上错误记录与截图重新打开issue
