### ISSUE TITLE
下载到的pdf分页为1K无效数据

### ISSUE THREAD

**Issue by WangXunpeng** [shylocks/51zhy_pdf#15]

**Comment by shylocks** [comment]
请提供编号、控制台输出等详细信息

**Comment by WangXunpeng** [comment]
控制台提示正常 重试多次可以获取正确数据。无效页比对是一样的。数据如下
d0 53 41 d2 f6 34 c6 24 b7 2a ad 39 ea e4 e1 6e
e8 02 a0 fd 50 a0 0a 23 bd fe 36 58 47 77 3e 96
bc 41 bf f5 5e

**Comment by zhubo** [comment]
let buffer = wordArrayToU8(c);
if (buffer.length < 2000) {
  console.log(`第${index}页PDF文件大小不正常：${buffer.length}`);
  return;
}
