### ISSUE TITLE
Failed to execute script merge_pdf

### ISSUE THREAD

**Issue by cbgilbert** [shylocks/51zhy_pdf#18]
![image](https://user-images.githubusercontent.com/30527760/74025016-009bcf80-49de-11ea-915b-a60a4005f448.png)

版本为v1.0.6里的merge_pdf.exe

**Comment by shylocks** [comment]
pypdf2确实存在这个问题，试过[stackoverflow](https://stackoverflow.com/a/52687771/10405090)的方法无解，推荐使用Adobe Acrobat DC合并
