### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by lnpygit** [shylocks/51zhy_pdf#2]
你好，我这两天也在做这个爬虫，但是得到的链接下载下来的pdf好像被处理过了，都不能正常显示，可以了解一下你是如何处理这个问题的吗？谢谢

**Comment by shylocks** [comment]
文件被AES加密过了，下载后需要解密

**Comment by lnpygit** [comment]
多谢，我只能确定出进行加密，但找不到加密的js代码，看了你的项目后知道解密的步骤了。
