### ISSUE TITLE
优化：直接下载整个 pdf 就可以了

### ISSUE THREAD

**Issue by lengthmin** [shylocks/51zhy_pdf#22]
![image](https://user-images.githubusercontent.com/13938334/74030052-106ce100-49e9-11ea-931a-6f388c70ba86.png)
可以不分页下载，直接下载下面那个  url 即可

**Comment by sqlsec** [comment]
我测试了好多 URL参数 链接大多数失效了 访问404  目前只能一个个分页下载了

**Comment by shylocks** [comment]
这个PDF下载下来无法解密

**Comment by lengthmin** [comment]
好吧 我试了一下，整个文件的 url 已经 404 了
