### ISSUE TITLE
应该还是存在特殊字符问题

### ISSUE THREAD

**Issue by Dark-Existed** [shylocks/51zhy_pdf#23]
![image](https://user-images.githubusercontent.com/24956657/74030933-38f5da80-49eb-11ea-9da7-8cc62925fbb1.png)
![image](https://user-images.githubusercontent.com/24956657/74030947-43b06f80-49eb-11ea-9fd1-c1b8590727dd.png)

两本不同的书 下下载过程中遇到的

**Comment by shylocks** [comment]
强烈建议不要开多个进程同时下载，没有对请求过快导致返回PDF文件错误做处理
