### ISSUE TITLE
大佬可以看下下面这个网站

### ISSUE THREAD

**Issue by filesdrive** [shylocks/51zhy_pdf#25]
https://www.keledge.com/wrap/pressResource
这个网站加密和电子工业悦读好像是类似的，上面好像是多个出版社的集合，能否看一下

**Comment by sqlsec** [comment]
介个是 电工社 之前推荐的移动端平台哎  我之前审查元素 发现客户端下载被隐藏起来了 然后去掉 hidden 下载的客户端 就是 可知

**Comment by filesdrive** [comment]
> 介个是 电工社 之前推荐的移动端平台哎 我之前审查元素 发现客户端下载被隐藏起来了 然后去掉 hidden 下载的客户端 就是 可知

好像资源更多一点
