### ISSUE TITLE
软件接口又没效了

### ISSUE THREAD

**Issue by lovexuanqi521** [shylocks/51zhy_pdf#30]

**Comment by sqlsec** [comment]
因访问流量过大，系统暂停免费使用以便进行升级。稍后会正常开放使用，给您带来的不便请谅解！

**Comment by zhubo** [comment]
之前52pojie发了悦读全本PDF下载工具（等注意到时已不可用了）。
现在全本已经不能下了，单页下载流量压力会大很多。
