### ISSUE TITLE
请问 deviceKey 怎么查到的

### ISSUE THREAD

**Issue by wlbksy** [shylocks/51zhy_pdf#6]
麻烦告知 deviceKey 怎么查询，是什么方法？简单描述一下就行，多谢

**Comment by shylocks** [comment]
deviceKey在js里有个默认值

**Comment by die9o** [comment]
deviceKey是LocalStorage里过来的，在访问书籍简介那里的index.html时，查找device就会发现有个hidden属性的input标签，同时混在Html里的script把它写到浏览器的localstorage去，后面的JS会把它写到cookie里去。我也是一下思维僵住了，找了几个JS都没找着。

**Comment by wlbksy** [comment]
混淆的js是怎么反混淆的呢，求问
